### ISSUE TITLE
12k+  weekly download!

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#48]
Some times ago I was switched our SF mirror to №1 'cause Gitlab has slow download speed. Add we can see now some statistics:
![sf](https://cloud.githubusercontent.com/assets/1550705/15993112/5f703516-30e5-11e6-9ee8-582c11c8f68e.png)

For example, @kuboosoft's [Postinstallerf](https://sourceforge.net/projects/postinstaller/) have only ~4.5k :smile: 

Sorry, but Gitlab was disabled the traffic statistics.

Popular packages:

* atom & electron 44/47
* mpv 105
* gnome-mpv 32
* vlc 161
* gstreamer 38
*                 -plugins-ugly 79
* xvidcore 94
* steam 15
* mplayer 24
* ffmpeg/libs  54/124
* nvidia-driver 18

It's says that we make a good thing. My congratulations.

**Comment by kuboosoft** [comment]
Hi, no touch my ego hahaha, because 'PostinstallerF' was disabled the track for the repository (fc22+fc23+fc24) ;) but It is a great news, ffmpeg + gstreamer +vlc  rules the world, and the project is a star and the people is using it, beautiful! haha

![trafic](http://s31.postimg.org/gly51gecb/trafic.png)

**Comment by paulcarroty** [comment]
20k :scream_cat:
