### ISSUE TITLE
unitedrpms updates gstreamer to unstable branch, replaces core Fedora packages

### ISSUE THREAD

**Issue by Mno-hime** [UnitedRPMs/packages#58]
https://unitedrpms.github.io states (emphasis is mine):
> We maintain the multimedia codecs and other software and addons which are **missing in the official Fedora repositories**. Play and work with multimedia, use the Web **without problems**.

I use UnitedRPMs on Fedora 24 and today I noticed that your repo provides update of gstreamer to version 1.9.1. However it is an unstable branch of gstreamer. As a consequence it also provides updates of core Fedora packages, e.g. gstreamer1, gstreamer1-plugins-base, and  gstreamer1-plugins-good etc. to version 1.9.1. I understand that you need to provide the same version former Fedora core packages to support upgrade to 1.9.1 of non-Fedora gstreamer packages.

What is the rationale for that? I originally understood UnitedRPMs a RPMFusion with different development model.

I believe that approach undermines "without problems" and "missing in the official Fedora repositories" pledges.

**Comment by paulcarroty** [comment]
Thank for your request, @Mno-hime. We doing mass rebuild for new `ffmpeg 3.1.1` together with **new stable** `gstreamer1 1.9.1` (check https://gstreamer.freedesktop.org/ for details) because it's faster, no need two rebuilds and works good.

New gstreamer1 is available for F25 and probably will be available for F24 in near future. If you don't want to use it - add to `/etc/dnf/dnf.conf`:

```
Exclude=gstreamer1*
```

**Comment by paulcarroty** [comment]
Downgraded to 1.8
