### ISSUE TITLE
[F24] gstreamer1-plugins-base multilib issue

### ISSUE THREAD

**Issue by alunux** [UnitedRPMs/packages#64]
```sh
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction check error:
  file /usr/share/appdata/gstreamer-base.appdata.xml from install of gstreamer1-plugins-base-1.8.2-1.fc24.i686 conflicts with file from package gstreamer1-plugins-base-1.8.2-1.fc24.x86_64

Error Summary
-------------
```

**Comment by paulcarroty** [comment]
@alunux thx for the report, please show which package you use - URPMS or [Fedora](https://bodhi.fedoraproject.org/updates/?packages=gstreamer1-plugins-base):

```
# dnf info gstreamer1-plugins-base
```

@kuboosoft, our `gstreamer1-plugins-base` have some serious difference between the Fedora package? Can we delete it from URPMS?

**Comment by kuboosoft** [comment]
@paulcarroty the user attempted install gstreamer1-plugins-base 32bits a machine of 64bits, It is impossible because other packages (64bits) depends the same libs (64bits); commonly exist similar paths between the packages, then it causes conflict. Sorry but we can't make changes here because if we move or deleted the "gstreamer-base.appdata.xml" the packages isn't seeable en "Gnome Software"...

**Comment by paulcarroty** [comment]
Closed as upstream bug.

@kuboosoft gstreamer1 1.9 broke **ALL** GNOME in F24. You can find the closed issue with this problem. Possible the same 'joy' with Xfce, AFAIR it's also use g1 for playback.

I can tell you more: g1 1.9 have the small chances for F24 including because it's non-stable relese, I'm was talk with Fedora maintainers.
